In [3]:
import numpy as np

## Creatge an array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4])
arr2.reshape(1,4)

array([[1, 2, 3, 4]])

In [10]:
import numpy as np

arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr3)
print(arr3.shape)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [14]:
import numpy as np

np.arange(0,10,2).reshape(5,1)

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [18]:
## Numpy Vectorized Operations

arr10=np.array([1,2,3,4,5])
arr20=np.array([10,20,30,40,50])

## Element wise addition
print("Addition:",arr10+arr20)

print("SUbstraction:",arr20-arr10)

print("Multiplication:",arr10*arr20)

Addition: [11 22 33 44 55]
SUbstraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]


In [ ]:
## Universal FUnctions
arry=np.array([2,3,4,5,6])
print(np.sqrt(arry))
print(np.exp(arry))
print(np.sin(arry))
print(np.log(arry))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [27]:
## Array slicing and indexing
import numpy as np
arry1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Array:\n",arry1)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
print(arry1[0][0])
arry1[1:,2:]

1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
print(arry1[0:2,2:])

[[ 3  4  5]
 [ 8  9 10]]


In [42]:
print(arry1[1:,1:3])

[[ 7  8]
 [12 13]]


In [44]:
## Modify the Array elements
arry1[0,0]=100
print(arry1)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [45]:
arry1[1:]=10
print(arry1)

[[100   2   3   4   5]
 [ 10  10  10  10  10]
 [ 10  10  10  10  10]]


In [46]:
## Statistical Concept: Normalization
## To have a means of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

#Normalize the data
normalized_data = (data-mean)/std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:",mean)

# Median
median = np.median(data)
print("Median:",median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

# Variance
variance = np.var(data)
print("Variance:",variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [49]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=9)]

array([5, 6, 7, 8, 9])